#!/usr/bin/env node

require('source-map-support').install();
const integration = require('../../build/test/integration');
const dest = process.argv[2] || 'reports';
integration.update(integration.process(), dest); // Update golden files
