#!/usr/bin/env node

require('source-map-support').install();
const stats = require('./build/index');
// tslint:disable-next-line: no-floating-promises
(async () => process.exit(await stats.process(process.argv[2], process.argv[3])))();
