#!/usr/bin/env node
'use strict'

const fs = require('fs');
const path = require('path');

const IN = path.resolve(__dirname, process.argv[2]);
const OUT = path.resolve(__dirname, process.argv[3]);

const formats = {};
for (const m of fs.readdirSync(IN)) {
  const month = path.resolve(IN, m);
  for (const f of fs.readdirSync(month)) {
    const format = path.resolve(month, f);
    const out = path.resolve(OUT, f);
    formats[f] = (formats[f] || 0);
    if (!fs.existsSync(out)) fs.mkdirSync(out, {recursive: true});
    for (const file of fs.readdirSync(format)) {
      const ordinal = `${++formats[f]}`.padStart(10, '0');
      fs.renameSync(path.resolve(format, file), path.resolve(out, `${ordinal}.log.json`));
    }
  }
}
