#!/usr/bin/env node

// Outputs a Tier Update report for Smogon's standard metagames based on
// differences between past usage reports. Expects to be given paths to
// reports directories for 1-3 months worth of statistics, SPECIFIED FROM
// MOST RECENT TO LEAST RECENT. Usage:
//
//   $ ./updates ../Pokemon-Showdown/Stats/2019-0{3,2,1}
//
// NOTE: It is important that the dependency on Pokemon-Showdown's core
// data is up to date, as the Tier Update report depends on each Pokemon's
// current tiering information to function correctly.

const fs = require('fs');
const path = require('path');
const stats = require('stats');
require('source-map-support').install();

if (process.argv.length < 3 || process.argv.length > 5) {
    console.error('updates path/to/month1 <path/to/month2> <path/to/month3>');
    process.exit(1);
}

// tslint:disable-next-line: no-floating-promises
(async () => {
  process.stdout.write(await stats.Reports.tierUpdateReport(process.argv.slice(2), (month, format) => {
    const baseline = format.startsWith('gen7ou') ? 1695 : 1630;
    const file = path.resolve(`${month}`, `${format}-${baseline}.txt`);
    return new Promise((resolve, reject) => {
      fs.readFile(file, 'utf8', (err, data) => {
        if (err) return err.code === 'ENOENT' ? resolve(undefined) : reject(err);
        resolve(data);
      });
    });
  }));
})();
