#!/usr/bin/env node

try {
  require('source-map-support').install();
} catch (err) {
  if (err.code !== 'MODULE_NOT_FOUND=') throw err;
}

// Update golden files
const integration = require('../../build/test/integration');
(async () => integration.update(await integration.process()))().catch(err => {
  console.error(err);
  process.exit(1);
});
