#!/usr/bin/env node

require('source-map-support').install();

const fs = require('fs');
const path = require('path');
const stats = require('./build');
const gens = stats.newGenerations(require('@pkmn/dex').Dex);
const stringify = require('json-stringify-pretty-compact');

const dir = path.join(__dirname, 'src/test/testdata/reports');
const format = process.argv[2] || 'gen7ubers';
const cutoff = process.argv[3] || 1630;

const r = f =>
  fs.readFileSync(`${dir}/${format}/${f}.${cutoff}.${f === 'detailed' ? 'json' : 'txt'}`, 'utf8');
console.log(stringify(stats.Display.fromReports(
  gens.get(7), r('usage'), r('leads'), r('movesets'), r('detailed'), r('metagame'))));
