name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: stats
    - uses: actions/checkout@v4
      with:
        repository: pkmn/engine
        path: engine
    - run: npm -C engine install --ignore-scripts
    - run: npm -C engine run compile
    - run: npm -C stats install
    - run: npm -C stats run test
